language: node_js
node_js:
  - 0.12
  - 0.1
  - iojs
before_install:
  - npm i -g npm@latest
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
env:
  secure: N0FTuA5Y62c1BBhuuCaOV1m8XUptsALQXz60Y7DUC6azLF0BIIEKJXjC2RseRmMOvR18+F/4gaU00/ZeTV9ugu7/YYLniymIA5AZdcjJPOR9iwnQu7Uc7bm8f/9jA7fTippxxIhWHHH7E6D2bMcNqy8cmnFgyPpSUk6Uf4eF3gLkS190BB7473Pp5+nFc79zwffF/9Lmceyb1e2GWff1nK23KaD1t979m84+cu8Yhgzf1fqU7krYNR1xuOH/PVK3fWMMaMPTfItyd723OrnqehjRGasvumXab5UwReIW0wN21ACzAyWwnhJM/fvjFWU4k6RfPWIZVshuZ9mT14hkHobpaMd83LjKEk7S98PY8PoSNoTWDUjlyAlvMoGGw8Mkv8eSxBomvvRtFouiQy8Qk4ts5PAkRvF64900yg3CJSpOdf/uvAy8LCt8A90uWQVqV47KouTLPm9LVXS+BO9/WZvKhazmnipQVvQgsbAV5WuL2qLBWrlj+RHuTIYqhXhPaqGOub1KTLTSBi4+l0Mj1H1p8LdnqPN2itdB8TfyGmr4Xv56Tvw427Aabn5XFmvJBmUaGsvs9C7AN41X0jVQo+yEhl2poMAkberVO1WNpp2sXu1m7IcFyFUZ9b2ZI1um5+Pbc9KlV3G2tNKjjjXQzXdZKhx7/CNqJg6F8Bg7SuU=
