language: node_js
node_js:
- 6
cache: yarn
before_script:
- yarn global add codecov
script:
- yarn run eslint
- yarn run flow
- yarn run cover
after_success:
- codecov
before_deploy: yarn postversion
deploy:
  skip_cleanup: true
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: SV4ayvQKih6rLRaCsxqOZKkeiihFuP8PaNV9BAbmMWv8xxZ7xpFmfT8if/1hpuEhCxurGGEG4geiuGygXiBcvy7v9ljZOUinB7rPiDF/74mZGtJdctiB9gP3+bxu2QwrWZRe0EUaHlhi6Bxt7FA9eTX0Y5wwDAqxpk4EXbPz152+dMFZ4UkHylCs3Y19mW+aYuevggOfbcY11TAD8yAMGBwZrfYgTARf3aSsSB3g4rAvkyY9NC+3yayz+CZ77fm+DjD5zwfOM0CLwmkKytXCOKrCGvb3C5fh3LbiJrNL3h4v0U6U9dlr6zePtHtPIjb/u+pL76NwhKPVjhK0dJR9oO9Kzd1sEQb+E3yd91PuMCJM4wczhK14zzpdQIUrQY+7dxOmvh78ZhQah4vUm2+y0+3lktSjOVOuSy1JNruFiPhdxJA0zIRaysWvh8eWVQU+LcOfgkTFlv0ufNIm7Tjovzy7nswFH4ZwnW4ucCvIiqeyoKxO6ovDw046848aJQj+KxKUeEkVFKvu54G1t8tJZ5jfi/SbayQCtgnWtaDVsm3vLxATnf+jviDlS+fv+cT+HRG8X2yYaORpluN5uxMUiJZfNa1zTq4oNbQNJTrU4BeMJ4jcurSkvFmW+TGSVAuLISfqx+J+WgOYfAJ/eAsik5zFwXP7M9tBgFn1A13D+qs=
  on:
    tags: true
    repo: intel-hpdd/socket-worker
